export const Strings = {
  connectTo: "Connect to",
  connectToKroger: "Connect to Kroger",
  location_selected: "Location Selected",
  selected_store_desc: "You have selected this store as your nearest location:",
  find_your_location: "Find your location",
  find_store_desc: "Enter your zip code and find your nearest Kroger store",
  search: "Search",
  mealDetail_info: "• 4 Servings • Medium",
  mealDetail_edit: "Edit",
  mealDetail_delete: "Delete",
  mealDetail_copyToMyMeals: "Copy Meal to Your Meals",
  _5_mins: "5 Mins",
  _10_mins: "10 Mins",
  _15_mins: "15 Mins",
  _20_mins: "20 Mins",
  _25_mins: "25 Mins",
  _30_mins: "30 Mins",
  _35_mins: "35 Mins",
  _40_mins: "40 Mins",
  _45_mins: "45 Mins",
  _50_mins: "50 Mins",
  _55_mins: "55 Mins",
  _60_mins: "60 Mins",
  mealDetail_ingredients: "Ingredients",
  mealDetail_instructions: "Instructions",
  mealDetail_description:
    "A rich and meaty sauce served over a bed of perfectly cooked spaghetti. A timeless family favorite that everyone will love.",
  mealDetail_ingredient_spaghetti: "Spaghetti",
  mealDetail_ingredient_spaghetti_qty: "400 g",
  mealDetail_ingredient_beef: "Ground Beef",
  mealDetail_ingredient_beef_qty: "500 g",
  mealDetail_ingredient_onion: "Onion",
  mealDetail_ingredient_onion_qty: "1 large",
  mealDetail_ingredient_garlic: "Garlic Cloves",
  mealDetail_ingredient_garlic_qty: "2",
  mealDetail_ingredient_tomatoes: "Chopped Tomatoes",
  mealDetail_ingredient_tomatoes_qty: "800 g",
  mealDetail_ingredient_paste: "Tomato Paste",
  mealDetail_ingredient_paste_qty: "2 tbsp",
  mealDetail_instruction_1:
    "Heat olive oil in a large pan. Sauté diced onion and garlic.",
  mealDetail_instruction_2: "Add ground beef and cook until browned.",
  mealDetail_instruction_3:
    "Stir in chopped tomatoes and tomato paste. Simmer for 20 minutes.",
  mealDetail_deleteMeal: "Delete Meal",
  mealDetail_deleteDesc:
    "This action is permanent and cannot be undone. You will lose access to this meal.",
  mealDetail_cancel: "Cancel",
  mealDetail_confirmDelete: "Delete",
  defaultServings_title: "Default Servings",
  defaultServings_subtitle:
    "You can set your meals servings for all your new meals.",
  defaultServings_label: "Servings",
  defaultServings_cancel: "Cancel",
  defaultServings_save: "Save",
  defaultServings_saving: "Saving...",
  createMeal_editMeal: "Edit Meal",
  createMeal_createMeal: "Create Meal",
  createMeal_addGlobalMeal: "Add Meal to Firebase",
  createMeal_basicInfo: "Basic Information",
  createMeal_mealName: "Meal Name",
  createMeal_mealName_placeholder: "e.g. Classic Spaghetti",
  createMeal_mealDescription: "Meal Description",
  createMeal_mealDescription_placeholder: "A short summary of the meal...",
  createMeal_mealDescription_edit_placeholder:
    "A rich and meaty sauce served over a bed of perfectly cooked spaghetti. A timeless family favorite that everyone will love.",
  createMeal_imageUrl: "Image URL",
  createMeal_imageUrl_placeholder: "https://...",
  createMeal_imageUrl_edit_placeholder:
    "https://myfood.com/image/Classic Spaghetti Bolognese",
  createMeal_upload: "Upload",
  createMeal_remove: "Remove",
  createMeal_prepTime: "Prep Time (min)",
  createMeal_minsSuffix: "Mins",
  createMeal_servings: "Servings",
  createMeal_difficulty: "Difficulty",
  createMeal_category: "Category",
  createMeal_ingredients: "Ingredients",
  createMeal_ingredientName: "Ingredient Name",
  createMeal_ingredientName_placeholder: "e.g. Tomato",
  createMeal_count: "Count",
  createMeal_unit: "Unit (weight)",
  createMeal_addIngredient: "Add Ingredient",
  createMeal_instruction: "Instruction",
  createMeal_addStep: "Add Step",
  createMeal_cancel: "Cancel",
  createMeal_discard: "Discard",
  createMeal_updateMeal: "Update Meal",
  createMeal_confirm: "Confirm",
  createMeal_copyMeal: "Copy Meal",
  createMeal_copyMealTitle: "Copy Meal",
  confirmationModal_title: "Are you sure?",
  confirmationModal_description: "This action cannot be undone.",
  confirmationModal_cancel: "Cancel",
  confirmationModal_confirm: "Confirm",
  resetPassword_description:
    "Enter your email and we'll send you a link to set a new password.",
  resetPassword_checkEmailTitle: "Check Your Email",
  // Worded so it reveals nothing about whether the address has an account —
  // see the enumeration note in services/passwordReset.ts.
  resetPassword_linkSent:
    "If an account exists for that email, we've sent it a link to set a new password. Check your spam folder if it doesn't arrive within a few minutes.",
  resetPassword_invalidEmail: "Please enter a valid email address.",
  resetPassword_networkError:
    "No connection. Check your internet and try again.",
  resetPassword_sendFailed:
    "Couldn't send the reset link. Please try again in a moment.",
  resetPassword_linkInvalid:
    "This reset link has expired or has already been used. Please request a new one.",
  resetPassword_weakPassword:
    "Please choose a stronger password — at least 8 characters.",
  resetPassword_ok: "OK",
  resetPassword_error: "Error",
  resetPassword_unexpectedError: "An unexpected error occurred",

  mealPlanSettings_title: "Meal Plan Settings",
  mealPlanSettings_customize:
    "Customize the number and names of meals for your daily plans.",
  mealPlanSettings_addEveningSnacks: "Add Evening Snacks",
  mealPlanSettings_addMoreType: "Add More Type",
  mealPlanSettings_limitReached: "Limit Reached (Max 9 Slots)",
  mealPlanSettings_save: "Save Settings",
  mealPlanSettings_mealNameEmpty: "Meal name cannot be empty",
  mealPlanSettings_noNewPlans: "No new meal plans to save",
  mealPlanSettings_saveSuccess: "Meal plans saved successfully",
  mealPlanSettings_saveError: "Failed to save meal plans. Please try again.",
  mealPlanSettings_deleteSuccess: "Meal plan deleted",
  mealPlanSettings_deleteError: "Failed to delete meal plan. Please try again.",
  createMealPlan_backToPlans: "Back to Plans",
  createMealPlan_yourMealPlan: "Your Meal Plan",
  createMealPlan_mySpecialMealPlan: "My special Meal Plan",
  divider_or: "OR",
  createMealPlan_startingDate: "Starting Date",
  createMealPlan_discard: "Discard",
  createMealPlan_save: "Save ",
  createMealPlan_update: "Update ",
  allergies_title: "Allergies & Intolerances",
  allergies_placeholder: "Press Enter to add a tag",
  allergies_save: "Save Allergies",
  lists_shoppingLists: "Shopping Lists",
  lists_created: "Created:",
  // The card counts `ingredients`, not meals — see 3_Lists.tsx.
  lists_item: "item",
  lists_items: "items",
  lists_markDone: "Mark Done",
  lists_viewList: "View List",
  plans_mealPlans: "Meal Plans",
  plans_started: "Started :",
  plans_created: "Created:",
  plans_viewPlan: "View Plan",
  plans_startPlan: "Start Plan",
  plans_noActivePlan: "No Active Plan",
  plans_testPlan: "Test Plan",
  plans_dayOf: "Day 3 of 7",
  plans_todaysMeal: "Today's Meal:",
  plans_breakfast: "Breakfast",
  plans_lunch: "Lunch",
  plans_dinner: "Dinner",
  plans_notPlanned: "Not planned",
  plans_avocadoToast: "Avocado Toast with...",
  plans_getShoppingList: "Get Shopping List",
  plans_pausePlan: "Pause Plan",
  plans_resumePlan: "Resume Plan",
  plans_yourOtherPlans: "Your Other Plans",
  plans_pauseMealPlan: "Pause Meal Plan?",
  plans_pauseDescription:
    "You can always resume the meal plan whenever you like to.",
  plans_cancel: "Cancel",
  plans_pause: "Pause",
  plans_pausing: "Pausing...",
  plans_updating: "Updating your plans...",
  meals_myMeals: "My Meals",
  meals_browseMeals: "Browse Meals",
  meals_searchPlaceholder: "Search your meals...",
  updateProfile_imageUploadFailed: "Image upload failed. Please try again.",
  updateProfileModal_title: "Update Profile",
  updateProfileModal_subtitle:
    "You can set your meals servings for all your new meals.",
  updateProfileModal_update: "Update",
  updateProfileModal_remove: "Remove",
  updateProfileModal_updateName: "Update Name",
  updateProfileModal_namePlaceholder: "Your Name",
  updateProfileModal_updateEmail: "Update Email",
  updateProfileModal_emailPlaceholder: "youemail@example.com",
  updateProfileModal_social: "Social",
  updateProfileModal_connectedWithGoogle: "Connected with Google",
  updateProfileModal_connectedWithApple: "Connected with Apple",
  updateProfileModal_cancel: "Cancel",
  sendShoppingList_title: "Send To Shopping List",
  sendShoppingList_subtitle:
    "You can choose from existing list to add this item’s shopping requirements.",
  sendShoppingList_createNewList: "Create New List",
  sendShoppingList_availableLists: "Available Lists",
  sendShoppingList_created: "Created:",
  sendShoppingList_add: "Add",
  sendShoppingList_cancel: "Cancel",
  sendShoppingList_confirm: "Confirm",
  meals_recentMeals: "Recent Meals",
  meals_yourMeals: "Your Meals",
  meals_noMealsFound: "No meals found",
  meals_recentMealsFound: "No recent meals found",
  meals_allMeals: "All Meals",
  mealCart: "Meal Cart",
  filterModal_filters: "Filters",
  filterModal_category: "Category",
  filterModal_difficulty: "Difficulty",
  filterModal_prepTime: "Prep Time",
  filterModal_reset: "Reset",
  filterModal_confirm: "Confirm",
  filterModal_breakfast: "Breakfast",
  filterModal_lunch: "Lunch",
  filterModal_dinner: "Dinner",
  filterModal_snacks: "Snacks",
  filterModal_easy: "Easy",
  filterModal_moderate: "Moderate",
  filterModal_challenging: "Challenging",
  filterModal_expert: "Expert",
  filterModal_prepTime_1: "< 5 Mins",
  filterModal_prepTime_2: "5 - 10 Mins",
  filterModal_prepTime_3: "10 - 15 Mins",
  filterModal_prepTime_4: "> 15 Mins",
  description:
    "Your smart meal planning assistant. Save recipes, plan weeks, and shop instantly.",
  createAccount: "Create Account",

  // Guest mode ("Continue as Guest"). Browsing meals and building plans / lists
  // must work without an account — see the anonymous-auth notes in authSlice.
  guest_continueAsGuest: "Continue as Guest",
  guest_failed: "Couldn't start a guest session. Please try again.",
  guest_signInUnavailable:
    "Guest access isn't available right now. Please create an account or log in.",
  guest_accountExists:
    "An account already exists for these details. Please log in instead — anything you saved as a guest stays on this device.",
  guest_badgeLabel: "Browsing as Guest",
  guest_createAccountCta: "Create an account",
  guest_accountSectionTitle: "Your Account",
  guest_accountSectionSubtitle:
    "You're browsing as a guest. Your meals, plans and lists are saved on this device only. Create a free account to sync them across your devices and keep them if you reinstall.",
  guest_krogerSubtitle:
    "Connecting a Kroger account needs a Meal Cart account. Create one to send your shopping list straight to your Kroger cart.",
  guest_profileLocked:
    "Create an account to set up a profile, add a photo and manage your password.",
  guest_exitGuest: "Exit guest mode",
  guest_exitTitle: "Exit guest mode?",
  guest_exitDescription:
    "Your guest session is tied to this device. Signing out permanently removes the meals, plans and lists you saved as a guest. Create an account first if you want to keep them.",
  guest_exitConfirm: "Exit anyway",

  imagePickerModal_selectImage: "Select Image",
  imagePickerModal_takePhoto: "Take Photo",
  imagePickerModal_chooseFromGallery: "Choose from Gallery",
  imagePickerModal_cancel: "Cancel",
  imagePickerModal_cameraPermission: "Camera permission is required!",
  imagePickerModal_mediaLibraryPermission:
    "Media library permission is required!",
  logIn: "Log In",
  continueWithGoogle: "Continue with Google",
  continue: "Continue",
  continueWithApple: "Continue with Apple",
  signUp: "Sign Up",
  signup: "Sign up",
  signIn: "Sign In",
  alreadyHaveAccount: "Already have an account?",
  newUser: "New to the app",
  createYourAccount: "Create Your Account",
  startJourney: "Start your journey to organized meals ",
  welcomeBack: "Welcome Back",
  forgotPassword: "Forgot Password?",
  back: "Back",
  next: "Next",
  getStarted: "Get Started",
  resetPassword: "Reset Password",
  sendResetLink: "Send Reset Link",
  rememberPassword: "Remember password?",
  saveAndLogin: "Save & Login",
  setNewPassword: "Set New Password",
  checkEmail: "Check Your Email",
  verify: "Verify",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  name: "Name",
  zipCode: "Zip Code",
  mealsAreSecure:
    "Your meal plans and recipes will be securely synced to your account.",
  userNotRegistered: "User is not registered in the database",
  // Firebase's email-enumeration protection collapses "no such user" and "wrong
  // password" into a single `auth/invalid-credential`, so the message has to
  // cover both — reporting "not registered" for a typo'd password sent users
  // off to sign-up, where they hit "email already in use" and got stuck.
  invalidCredentials: "Incorrect email or password. Please try again.",
  tooManyAttempts:
    "Too many failed attempts. Please wait a few minutes or reset your password.",
  googleSignInMisconfigured:
    "Google Sign-In isn't available for this app version. Please log in with your email and password.",
  // Apple sign-in failure messages. These are deliberately distinct from one
  // another: the old code funnelled every Apple *and* Firebase error into one
  // "Failed to sign in with Apple" string, which made the cause unknowable from
  // a bug report. See the switch in services/appleSignin.ts.
  appleSignIn_cancelled: "Sign-in was cancelled",
  appleSignIn_unsupportedDevice:
    "Apple Sign In isn't available on this device. Please use Google or email sign-in.",
  appleSignIn_entitlementMissing:
    "Apple Sign In isn't set up for this app version. Please use Google or email sign-in.",
  appleSignIn_providerDisabled:
    "Apple sign-in isn't enabled for Meal Cart yet. Please use Google or email sign-in.",
  appleSignIn_rejectedCredential:
    "Apple couldn't verify this sign-in. Please try again, or use Google or email sign-in.",
  appleSignIn_accountExists:
    "An account already exists for this email address. Please sign in with the method you used originally.",
  appleSignIn_noIdentityToken: "No identity token received from Apple",
  appleSignIn_networkError: "No connection. Check your internet and try again.",
  appleSignIn_failed: "Couldn't sign in with Apple. Please try again.",
  googleSignIn_failed: "Couldn't sign in with Google. Please try again.",
  googleSignIn_providerDisabled:
    "Google sign-in isn't enabled for Meal Cart yet. Please use email sign-in.",
  signinSuccessful: "Signin successful",
  signupSuccessfully: "Account created successfully!",
  signinFailed: "Signin failed",
  registrationFailed: "Registration failed",
  loginFailed: "Login failed",
  mealAdded: "Meal added successfully",
  signinDescription: "Log in to continue your meal planning.",
  home_mealCart: "MealCart",
  home_greeting: "Hello there!",
  home_subgreeting: "What delicious meal are you planning today?",
  home_nextMeal: "Your Next Meal",
  home_viewAll: "View All",
  home_noUpcomingMeals: "No upcoming meals. Add one!",
  home_mealCardDescription:
    "Some sort of description etc. Big Card if we want more information here",
  home_view: "View",
  home_addNewMeal: "Add New Meal",
  home_myMeals: "My Meals",
  home_addMealToFirebase: "Add Meal to Firebase",
  home_recentMeals: "Recent Meals",
  home_viewAllRecent: "View All",
  home_moderate: "Moderate",
  home_lunch: "Lunch",
  home_dinner: "Dinner",
  dietaryPreferences_title: "Dietary Preferences",
  dietaryPreferences_save: "Save Preferences",
  dietaryPreferences_vegetarian: "Vegetarian",
  dietaryPreferences_vegan: "Vegan",
  dietaryPreferences_glutenFree: "Gluten-Free",
  dietaryPreferences_keto: "Keto",
  dietaryPreferences_paleo: "Paleo",
  dietaryPreferences_pescatarian: "Pescatarian",
  dietaryPreferences_dairyFree: "Dairy-Free",
  passwordReset_title: "Password Reset",
  passwordReset_currentPassword: "Current Password",
  passwordReset_newPassword: "New Password",
  passwordReset_confirmNewPassword: "Confirm New Password",
  passwordReset_updatePassword: "Update Password",
  profile_title: "Profile",
  profile_name: "Alex Doe",
  profile_email: "alex.doe@email.com",
  profile_mealCookingPreferences: "MEAL & COOKING PREFERENCES",
  profile_dietaryPreferences: "Dietary Preferences",
  profile_vegetarian: "Vegetarian",
  profile_allergies: "Allergies & Intolerances",
  profile_peanuts: "Peanuts",
  nA: "N/A",
  preferencesSavedSuccessfully: "Preferences saved successfully!",
  failedToSavePreferences: "Failed to save preferences",
  profile_mealPlanSettings: "Meal Plan Settings",
  profile_defaultServings: "Default Servings",
  profile_defaultServingsSubtitle: "2 People",
  profile_accountSecurity: "ACCOUNT & SECURITY",
  profile_krogerAccount: "ACCOUNT",
  profile_krogerStatus: "Status",
  profile_krogerConnected: "Connected",
  profile_krogerDisconnected: "Disconnected",
  profile_krogerConnect: "Connect",
  profile_krogerDefaultStore: "Default Store",
  profile_krogerChange: "Change",
  profile_krogerSelectStore: "Select Store",
  profile_krogerDisconnectedSubtitle:
    "Connect your Kroger account to choose a default store and send items to cart.",
  profile_krogerNoStore: "No default store selected yet.",
  profile_krogerDisconnectAccount: "Disconnect Account",
  profile_krogerDisconnectTitle: "Disconnect Kroger Account?",
  profile_krogerDisconnectDescription:
    "This will remove your Kroger connection and saved store from Meal Cart.",
  profile_changePassword: "Change Password",
  profile_deleteAccount: "Delete Account",
  profile_logout: "Logout",
  profile_appSettings: "APP SETTINGS",
  profile_privacyPolicy: "Privacy Policy",
  profile_termsOfService: "Terms of Service",
  error_unableToOpenLink: "Unable to open link",
  profile_deleteAccountTitle: "Delete Account?",
  profile_deleteAccountDescription:
    "This action is permanent and cannot be undone. All your meals, plans, and lists will be lost.",
  profile_cancel: "Cancel",
  profile_confirmDelete: "Delete",
  // `deleteUser` refuses on a session older than a few minutes. Deleting the
  // profile doc first used to leave the account half-deleted (auth user alive,
  // profile gone), which locked the user out of both sign-in and sign-up.
  profile_deleteAccountReauth:
    "For your security, please log out and log back in, then delete your account again.",
  testMealPlan_backToPlans: "Back to Plans",
  testMealPlan_title: "Test Plan",
  testMealPlan_startedOn: "Started on 27/09/2025",
  testMealPlan_removeTitle: "Remove Meal Plan?",
  shoppingList_removeTitle: "Remove Shopping List?",
  testMealPlan_removeDescription:
    "Meal Plan will be removed and can no longer be accessible.",
  shoppingList_removeDescription:
    "Shopping List will be removed and can no longer be accessible.",
  testMealPlan_cancel: "Cancel",
  testMealPlan_remove: "Remove",
  testMealPlan_removing: "Removing...",
  days: {
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
  },
  testMealPlan_breakfast: "Breakfast",
  testMealPlan_lunch: "Lunch",
  testMealPlan_mySpecialMorningToast: "My special Morning Toast",
  testMealPlan_mySpecialBurger: "My Special Burger",
  testMealPlan_10min: "10 min",
  testMealPlan_15min: "15 min",
  testMealPlan_easy: "Easy",
  testMealPlan_medium: "Medium",
  testMealPlan_hard: "Hard",
  testPlanShopping_backToLists: "Back to Lists",
  testPlanShopping_title: "Unknown List",
  testPlanShopping_1meal: "1 meal",
  testPlanShopping_progress: "Progress",
  testPlanShopping_progressText: "2/4",
  testPlanShopping_bakery: "Bakery",
  testPlanShopping_wholeGrainBread: "Whole-grain bread",
  testPlanShopping_wholeGrainBreadAmount: "1 slice (Avocado Toast with Egg)",
  testPlanShopping_dairy: "Dairy",
  testPlanShopping_egg: "Egg",
  testPlanShopping_eggAmount: "1 (Avocado Toast with Egg)",
  testPlanShopping_pantry: "Pantry",
  testPlanShopping_redPepperFlakes: "Red pepper flakes",
  testPlanShopping_redPepperFlakesAmount: "1 pinch (Avocado Toast with Egg)",
  testPlanShopping_produce: "Produce",
  testPlanShopping_avocado: "Avocado",
  testPlanShopping_avocadoAmount: "0.5 (Avocado Toast with Egg)",
  testPlanShopping_krogerChooseModality:
    "Choose how you would like to receive your items.",
  testPlanShopping_krogerDelivery: "Delivery",
  testPlanShopping_krogerPickup: "Pickup",
  testPlanShopping_krogerSendToCart: "Send to",
  testPlanShopping_krogerCart: "Cart",
  testPlanShopping_krogerSelectModality: "Please select Delivery or Pickup",
  testPlanShopping_krogerNoItems: "No Kroger items found in this list",
  testPlanShopping_krogerSuccess: "Success",
  // The Kroger app can keep showing a cached cart after a successful add, so
  // the message points at kroger.com rather than letting a stale app screen
  // read as a failed transfer.
  testPlanShopping_krogerSuccessMessage:
    "Items have been added to your Kroger cart!\n\nIf the Kroger app still shows an empty cart, open your cart at kroger.com — the app can take a while to refresh.",
  testPlanShopping_krogerError: "Error",
  testPlanShopping_krogerErrorMessage: "Failed to add items to Kroger cart",
  testPlanShopping_krogerResendTitle: "Already sent to Kroger",
  testPlanShopping_krogerResendMessage:
    "items are already in your Kroger cart from a previous transfer. Sending again will add another copy of them.",
  testPlanShopping_krogerResendCancel: "Cancel",
  testPlanShopping_krogerResendConfirm: "Send anyway",
  testPlanShopping_krogerPartialTitle: "Partly sent to Kroger",
  testPlanShopping_krogerPartialMessage:
    "items were added to your Kroger cart. Kroger would not accept these — they are usually not carried at your selected store:",
  testPlanShopping_krogerScopeHint:
    "Kroger did not grant this app permission to write to your cart. Disconnect Kroger in Profile, reconnect, and make sure you accept the cart permission on Kroger's consent screen.",
  testPlanShopping_krogerAllRejected: "Kroger refused every item. It reported:",
  testPlanShopping_krogerReconnectHint:
    "Your Kroger session may have expired. Reconnect your Kroger account from Profile and try again.",
  // Shown on a Kroger row whose recipe amount is a measurement rather than a
  // package count, so the user can see the cart gets one package of it.
  testPlanShopping_krogerCartQuantity: "Kroger cart:",
  testPlanShopping_meal: "meal",
  testPlanShopping_meals: "meals",
  testPlanShopping_unknownIngredient: "Unknown Ingredient",
  testPlanShopping_noUnit: "No unit",
  testPlanShopping_errorUpdating: "Error updating ingredient status: ",
  testPlanShopping_selectAll: "Select All",
  testPlanShopping_unselectAll: "Unselect All",
  introScreen_title: "Welcome to MealCart",
  introScreen_description: "All your meal planning, simplified in one place.",
  newPassword_description:
    "Your new password must be different from previous ones.",
  newPassword_success: "Password updated successfully!",
  newPassword_updateFailed: "Update Failed",
  newPassword_error: "Error",
  newPassword_unexpectedError: "An unexpected error occurred",
  welcomeMealCart_slide1_heading: "Welcome to MealCart  ",
  welcomeMealCart_slide1_subheading:
    "All your meal planning, simplified in one place.",
  welcomeMealCart_slide2_heading: "Build Your Perfect week",
  welcomeMealCart_slide2_subheading:
    "Create custom meal plans from your favorite receipes with just a few taps",
  welcomeMealCart_slide3_heading: "Shop Smarter,  Not Harder",
  welcomeMealCart_slide3_subheading:
    "Automatically generate an organized shopping list from your plan. Never forget an ingredient again.",
  welcomeMealCart_back: "Back",
  welcomeMealCart_getStarted: "Get Started",
  welcomeMealCart_next: "Next",
  addItemToList_title: "Select Meals to Shop For",
  addItemToList_subtitle:
    "Choose one or more meals to generate a combined list.",
  addItemToList_searchPlaceholder: "Search your meals...",
  search_store: "Search Store...",
  selectKrogerStore_searchingLocations: "Searching locations",
  selectKrogerStore_subtitle:
    "Find your store location and select it to begin connecting Meal Cart with your Kroger store.",
  selectKrogerStore_cancel: "Cancel",
  selectKrogerStore_selectStore: "Select Store",
  addItemToList_addManualLabel: "Add item Manually",
  addItemToList_searchIngredient:
    "Search Kroger products or your ingredients...",
  addItemToList_yourIngredientsLabel: "From your selected meals",
  addItemToList_krogerSectionLabel: "Kroger products",
  addItemToList_krogerSearching: "Searching Kroger...",
  addItemToList_krogerNoResults:
    "No Kroger products found. Try another search.",
  addItemToList_krogerNoStore:
    "Connect your Kroger account and pick a store to search products here.",
  addItemToList_add: "Add",
  addItemToList_cancel: "Cancel",
  addItemToList_generateList: "Generate List",
  createList_createNewList: "Create New List",
  createPlan_selectAMeal: "Select a Meal",
  createList_listDetails: "List Details",
  createList_listName: "List Name",
  createList_listName_placeholder: "Classic Spaghetti",
  createList_shoppingDay: "Shopping Day",
  createList_shoppingDay_placeholder: "date",
  createList_items: "Items",
  createList_importedFrom: "imported from [Meal Name]",
  createList_addExtraItems: "Add extra items",
  createList_discard: "Discard",
  createList_saveShoppingList: "Save Shopping List",
  createList_category: "Category",
  mealUpdated: "Meal updated successfully",
  shoppingList_deleted: "Shopping list deleted successfully",
  error_deleting_shoppingList: "Error deleting shopping list",
  error_creating_meal: "Error creating meal",
  error_updating_meal: "Error updating meal",
  meal_deleted: "Meal deleted successfully",
  meal_copied: "Meal copied to your meals",
  error_copying_meal: "Error copying meal",
  error_deleting_meal: "Error deleting meal",
  error_occurred_deleting_meal: "An error occurred while deleting the meal",
  units: {
    _100_grams: "100 grm",
    _200_grams: "200 grm",
    _1_kg: "1 kg",
    _50_ml: "50 ml",
    _100_ml: "100 ml",
    _250_ml: "250 ml",
    _500_ml: "500 ml",
    _1_litre: "1 Litre",
    tablespoon: "tablespoon",
    teaspoon: "teaspoon",
    cup: "cup",
  },
  // Global unit list used for any ingredient that isn't mapped to a specific
  // category/type (e.g. a plain ingredient name). Ordered small -> large so it
  // scrolls sensibly in the unit picker.
  globalUnitOptions: [
    "piece",
    "slice",
    "clove",
    "pinch",
    "handful",
    "teaspoon",
    "tablespoon",
    "cup",
    "can",
    "package",
    "tub",
    "bottle",
    "jar",
    "bunch",
    "50 ml",
    "100 ml",
    "250 ml",
    "500 ml",
    "1 Litre",
    "100 grm",
    "200 grm",
    "500 grm",
    "1 kg",
    "oz",
    "to taste",
  ],
  // Default count applied to a newly added ingredient.
  defaultCount: "1",
  fruit: "fruit",
  vegetable: "vegetable",
  meat: "meat",
  liquid: "liquid",
  veggies: "veggie",
  error_fetching_dietary_preferences: "Failed to fetch dietary preferences",
  error_adding_meal_plan: "Failed to add meal plan",
  error_deleting_meal_plan: "Failed to delete meal plan",
  error_updating_meal_plan: "Failed to update meal plan",
  error_fetching_meal_plans: "Failed to fetch meal plans",
  error_adding_plan: "Failed to add plan",
  error_fetching_plans: "Failed to fetch plans",
  error_updating_plan: "Failed to update plan",
  error_deleting_plan: "Failed to delete plan",
  plan_saved_successfully: "Plan saved successfully!",
  plan_updated_successfully: "Plan updated successfully!",
  error_enter_plan_name: "Please enter a name for the meal plan.",
  error_select_meal_for_any_day: "Please select at least one meal for any day.",
  meals: "meals",
  unknown_plan: "Unknown Plan",
  profile_servings: "People",
  clearFilters: "Clear Filters",
  meal_not_found: "Meal not found",
  kroger_signup_desc:
    "Link your Meal Cart account with your Kroger account to send meals directly to your Kroger cart for pickup or delivery!",
  skip_for_now: "Skip For Now",
  store: "Store",
  addKrogerIngredient_title: "Add Ingredient",
  addKrogerIngredient_subtitle:
    "Searching available items at your connected Kroger location",
  addKrogerIngredient_searchPlaceholder: "Search ingredient...",
  addKrogerIngredient_cancel: "Cancel",
  addKrogerIngredient_addIngredient: "Add Ingredient",
  addKrogerIngredient_searching: "Searching products...",
  addKrogerIngredient_noResults: "No products found. Try another search.",
  addKrogerIngredient_searchPrompt:
    "Search for an ingredient to see available products",
  addKrogerIngredient_addManualResult: "Add Typed Ingredient",
  addKrogerIngredient_lowStock: "Low Stock",
  addKrogerIngredient_inStore: "In Store",
  addKrogerIngredient_curbside: "Curbside",
  addKrogerIngredient_delivery: "Delivery",
  addKrogerIngredient_shipToHome: "Ship To Home",
  addKrogerIngredient_outOfStock: "Out of Stock",
  addKrogerIngredient_each: "each",
  addKrogerIngredient_change: "Change",
  profile_krogerConnectAccount: "Connect Account",
  profile_krogerTokenExpiredSubtitle:
    "Your Kroger session has expired. Please reconnect to continue using Kroger features.",
};
